DROP DATABASE IF EXISTS BD_ECOLE;

CREATE DATABASE BD_ECOLE;

USE BD_ECOLE;

CREATE
  TABLE CLASSE
  (
    CLASSE_ID    INTEGER auto_increment NOT NULL ,
    CLAS_NOM   CHAR (6 ) NOT NULL ,
    CONSTRAINT CLASSE_PK PRIMARY KEY (CLASSE_ID)
  )ENGINE=InnoDB, CHARSET=UTF8;

CREATE
  TABLE PERSONNE
  (
    PERSONNE_ID  INTEGER auto_increment NOT NULL ,
    PERS_NOM VARCHAR (30 ) NOT NULL,
    PERS_PRENOM VARCHAR (30 ) NOT NULL ,
    PERS_SEXE           CHAR (1 ) NOT NULL ,
    PERS_ADR            VARCHAR (50 ) NOT NULL ,
    PERS_CP             CHAR (5 ) NOT NULL ,
    PERS_VILLE          VARCHAR (50 ) NOT NULL ,
    PERS_DATE_NAISSANCE DATE NOT NULL ,
    PERS_EMAIL          VARCHAR (100 ) ,
    PERS_TEL            CHAR (10 ) ,
    CONSTRAINT PERSONNE_PK PRIMARY KEY (PERSONNE_ID)
  )ENGINE=InnoDB, CHARSET=UTF8;

CREATE
  TABLE ELEVE
  (
    ELEVE_ID INTEGER NOT NULL ,
    CONSTRAINT ELEVE_PK PRIMARY KEY (ELEVE_ID)
  )ENGINE=InnoDB, CHARSET=UTF8;

CREATE
  TABLE PROFESSEUR
  (
    PROFESSEUR_ID INTEGER NOT NULL,
    CONSTRAINT PROFESSEUR_PK PRIMARY KEY (PROFESSEUR_ID)
  )ENGINE=InnoDB, CHARSET=UTF8;

CREATE
  TABLE MATIERE
  (
    MATIERE_ID  INTEGER auto_increment NOT NULL ,
    MATR_NOM_COURT VARCHAR (5 ) NOT NULL,
    MATR_NOM_LONG VARCHAR (255 ) NOT NULL,
    CONSTRAINT MATIERE_PK PRIMARY KEY (MATIERE_ID)
  )ENGINE=InnoDB, CHARSET=UTF8;

CREATE
  TABLE SESSION
  (
    SESSION_ID INTEGER auto_increment NOT NULL ,
    SESS_DATES  CHAR (9 ) ,
    CONSTRAINT SESSION_PK PRIMARY KEY (SESSION_ID)
  )ENGINE=InnoDB, CHARSET=UTF8;
  
CREATE
  TABLE APPARTENIR
  (
    APPA_ELEV_ID INTEGER NOT NULL ,
    APPA_SESS_ID INTEGER NOT NULL ,
    APPA_CLAS_ID INTEGER NOT NULL ,
    CONSTRAINT APPARTENIR_PK PRIMARY KEY (APPA_ELEV_ID, APPA_SESS_ID, APPA_CLAS_ID)
  )ENGINE=InnoDB, CHARSET=UTF8;

CREATE
  TABLE ENSEIGNER
  (
    ENSG_PROF_ID INTEGER NOT NULL ,
    ENSG_MATR_ID  INTEGER NOT NULL ,
    ENSG_CLAS_ID  INTEGER NOT NULL ,
    ENSG_SESS_ID  INTEGER NOT NULL ,
    CONSTRAINT ENSEIGNER_PK PRIMARY KEY (ENSG_PROF_ID, ENSG_MATR_ID, ENSG_CLAS_ID, ENSG_SESS_ID)
  )ENGINE=InnoDB, CHARSET=UTF8;

CREATE
  TABLE EVALUATION
  (
    EVALUATION_ID      INTEGER auto_increment NOT NULL ,
    EVAL_DATE    DATE NOT NULL ,
    EVAL_MATR_ID  INTEGER NOT NULL ,
    EVAL_COEF    INTEGER NOT NULL ,
    EVAL_CLAS_ID  INTEGER NOT NULL ,
    EVAL_PROF_ID INTEGER NOT NULL ,
    CONSTRAINT EVALUATION_PK PRIMARY KEY (EVALUATION_ID)
  )ENGINE=InnoDB, CHARSET=UTF8;

CREATE
  TABLE NOTES
  (
    NOTE_ELEV_ID   INTEGER NOT NULL ,
    NOTE_EVAL_ID INTEGER NOT NULL ,
    NOTE_OBTENUE INTEGER NOT NULL ,
    CONSTRAINT NOTES_PK PRIMARY KEY (NOTE_ELEV_ID, NOTE_EVAL_ID)
  )ENGINE=InnoDB, CHARSET=UTF8;


ALTER TABLE APPARTENIR ADD CONSTRAINT APPARTENIR_ELEVE_FK
FOREIGN KEY ( APPA_ELEV_ID ) REFERENCES ELEVE ( ELEVE_ID ) ;

ALTER TABLE APPARTENIR ADD CONSTRAINT ELEV_CLAS_FK FOREIGN
KEY ( APPA_CLAS_ID ) REFERENCES CLASSE ( CLASSE_ID ) ;

ALTER TABLE APPARTENIR ADD CONSTRAINT ELEV_SESS_FK FOREIGN
KEY ( APPA_SESS_ID ) REFERENCES SESSION ( SESSION_ID ) ;

ALTER TABLE ELEVE ADD CONSTRAINT ELEV_PERS_FK FOREIGN KEY (
ELEVE_ID ) REFERENCES PERSONNE ( PERSONNE_ID ) ;

ALTER TABLE ENSEIGNER ADD CONSTRAINT ENSG_CLAS_FK FOREIGN
KEY ( ENSG_CLAS_ID ) REFERENCES CLASSE ( CLASSE_ID ) ;

ALTER TABLE ENSEIGNER ADD CONSTRAINT ENSG_MATR_FK
FOREIGN KEY ( ENSG_MATR_ID ) REFERENCES MATIERE ( MATIERE_ID ) ;

ALTER TABLE ENSEIGNER ADD CONSTRAINT ENSG_PROF_FK
FOREIGN KEY ( ENSG_PROF_ID ) REFERENCES PROFESSEUR ( PROFESSEUR_ID ) ;

ALTER TABLE ENSEIGNER ADD CONSTRAINT ENSG_SESS_FK
FOREIGN KEY ( ENSG_SESS_ID ) REFERENCES SESSION ( SESSION_ID ) ;

ALTER TABLE EVALUATION ADD CONSTRAINT EVAL_CLAS_FK
FOREIGN KEY ( EVAL_CLAS_ID ) REFERENCES CLASSE ( CLASSE_ID ) ;

ALTER TABLE EVALUATION ADD CONSTRAINT EVAL_MATR_FK
FOREIGN KEY ( EVAL_MATR_ID ) REFERENCES MATIERE ( MATIERE_ID ) ;

ALTER TABLE EVALUATION ADD CONSTRAINT EVAL_PROF_FK
FOREIGN KEY ( EVAL_PROF_ID ) REFERENCES PROFESSEUR ( PROFESSEUR_ID ) ;

ALTER TABLE NOTES ADD CONSTRAINT NOTE_ELEV_FK FOREIGN KEY (
NOTE_ELEV_ID ) REFERENCES ELEVE ( ELEVE_ID ) ;

ALTER TABLE NOTES ADD CONSTRAINT NOTE_EVAL_FK FOREIGN KEY
( NOTE_EVAL_ID ) REFERENCES EVALUATION ( EVALUATION_ID ) ;

ALTER TABLE PROFESSEUR ADD CONSTRAINT PROF_PERS_FK
FOREIGN KEY ( PROFESSEUR_ID ) REFERENCES PERSONNE ( PERSONNE_ID ) ;
