INSERT INTO PERSONNE (PERS_NOM, PERS_PRENOM, PERS_SEXE, PERS_ADR, PERS_CP, PERS_VILLE, PERS_DATE_NAISSANCE, PERS_EMAIL, PERS_TEL) VALUES ('DUPONT', 'Mireille', 'F', '65 rue Bernard Chochoy', '62570', 'WIZERNES', '1969-04-29', 'candy@monadresseemail.com', '0365876976');
INSERT INTO PERSONNE (PERS_NOM, PERS_PRENOM, PERS_SEXE, PERS_ADR, PERS_CP, PERS_VILLE, PERS_DATE_NAISSANCE, PERS_EMAIL, PERS_TEL) VALUES ('REBREDO', 'Tony', 'M', '10 rue de Kerdual', '29100', 'COMBRIT', '1992-04-12', 'tony@monadresseemail.com', NULL);
INSERT INTO PERSONNE (PERS_NOM, PERS_PRENOM, PERS_SEXE, PERS_ADR, PERS_CP, PERS_VILLE, PERS_DATE_NAISSANCE, PERS_EMAIL, PERS_TEL) VALUES ('MARCO', 'Michel', 'M', '106 rue des acacias', '35760', 'MONTGERMONT', '1990-06-30', 'michel@monadresseemail.com', '0299876976');
INSERT INTO PERSONNE (PERS_NOM, PERS_PRENOM, PERS_SEXE, PERS_ADR, PERS_CP, PERS_VILLE, PERS_DATE_NAISSANCE, PERS_EMAIL, PERS_TEL) VALUES ('SANCHEZ', 'Carlos', 'M', '10 rue Belle Ville', '56600', 'LANESTER', '1992-04-29', 'carlos@monadresseemail.com', NULL);
INSERT INTO PERSONNE (PERS_NOM, PERS_PRENOM, PERS_SEXE, PERS_ADR, PERS_CP, PERS_VILLE, PERS_DATE_NAISSANCE, PERS_EMAIL, PERS_TEL) VALUES ('COAT', 'José', 'M', '40 rue de Lorient', '56600', 'LANESTER', '1992-10-12', NULL, '0297876976');
INSERT INTO PERSONNE (PERS_NOM, PERS_PRENOM, PERS_SEXE, PERS_ADR, PERS_CP, PERS_VILLE, PERS_DATE_NAISSANCE, PERS_EMAIL, PERS_TEL) VALUES ('MARSON', 'Marine', 'F', '65 rue de Luscanen', '56600', 'LANESTER', '1991-11-03', 'marine@monadresseemail.com', '0297876976');
INSERT INTO PERSONNE (PERS_NOM, PERS_PRENOM, PERS_SEXE, PERS_ADR, PERS_CP, PERS_VILLE, PERS_DATE_NAISSANCE, PERS_EMAIL, PERS_TEL) VALUES ('MILANO', 'Karine', 'F', '51 rue de mars', '29100', 'COMBRIT', '1991-05-05', 'karine@monadresseemail.com', '0298876976');
INSERT INTO PERSONNE (PERS_NOM, PERS_PRENOM, PERS_SEXE, PERS_ADR, PERS_CP, PERS_VILLE, PERS_DATE_NAISSANCE, PERS_EMAIL, PERS_TEL) VALUES ('DCAPRIO', 'Marco', 'M', '01 route de l\'ile-tudy', '29100', 'COMBRIT', '1992-01-01', 'marco@monadresseemail.com', NULL);
INSERT INTO PERSONNE (PERS_NOM, PERS_PRENOM, PERS_SEXE, PERS_ADR, PERS_CP, PERS_VILLE, PERS_DATE_NAISSANCE, PERS_EMAIL, PERS_TEL) VALUES ('MESSON', 'John', 'M', '25 rue du Moustoir', '56100', 'LORIENT', '1957-02-14', NULL, '0297876976');

/*
UPDATE `db_ecole`.`personne` SET `PERS_TEL`=NULL WHERE `PERSONNE_ID`='11';
UPDATE `db_ecole`.`personne` SET `PERS_TEL`=NULL WHERE `PERSONNE_ID`='13';
UPDATE `db_ecole`.`personne` SET `PERS_TEL`=NULL WHERE `PERSONNE_ID`='17';
*/
/*
UPDATE `db_ecole`.`personne` SET `PERS_EMAIL`=NULL WHERE `PERSONNE_ID`='14';
UPDATE `db_ecole`.`personne` SET `PERS_EMAIL`=NULL WHERE `PERSONNE_ID`='18';
*/


-- SET SQL_SAFE_UPDATES = 0;

/*DELETE FROM PROFESSEUR WHERE PROFESSEUR_ID IS NOT NULL;
DELETE FROM PERSONNE;
*/
INSERT INTO PROFESSEUR (PROFESSEUR_ID) SELECT PERSONNE_ID FROM PERSONNE WHERE YEAR(PERS_DATE_NAISSANCE) < '1980';
INSERT INTO ELEVE (ELEVE_ID) SELECT PERSONNE_ID FROM PERSONNE WHERE PERSONNE_ID NOT IN (SELECT PROFESSEUR_ID FROM PROFESSEUR);

INSERT INTO CLASSE (CLAS_NOM) VALUES ('1TSSIO');
INSERT INTO CLASSE (CLAS_NOM) VALUES ('2TSSIO');

INSERT INTO SESSION (SESS_DATES) VALUES ('2010-2011');
INSERT INTO SESSION (SESS_DATES) VALUES ('2011-2012');
INSERT INTO SESSION (SESS_DATES) VALUES ('2012-2013');
INSERT INTO SESSION (SESS_DATES) VALUES ('2013-2014');
INSERT INTO SESSION (SESS_DATES) VALUES ('2014-2015');
INSERT INTO SESSION (SESS_DATES) VALUES ('2015-2016');

/*ALTER TABLE MATIERE CHANGE MATR_NOM MATR_NOM_COURT VARCHAR(5 );
ALTER TABLE MATIERE ADD (MATR_NOM_LONG VARCHAR(30 ) NOT NULL);*/
/*ALTER TABLE MATIERE MODIFY MATR_NOM_LONG VARCHAR(255 ) NOT NULL;*/
INSERT INTO MATIERE (MATR_NOM_COURT, MATR_NOM_LONG) VALUES ('SI3', 'Exploitation des bases de données');
INSERT INTO MATIERE (MATR_NOM_COURT, MATR_NOM_LONG) VALUES ('SLAM1', 'Exploitation d\'un schéma de données');
INSERT INTO MATIERE (MATR_NOM_COURT, MATR_NOM_LONG) VALUES ('SI4', 'Bases de la programmation');
INSERT INTO MATIERE (MATR_NOM_COURT, MATR_NOM_LONG) VALUES ('SLAM3', 'Conception et adaptation d\'une base de données');

INSERT INTO APPARTENIR VALUES (2, 1, 1);
INSERT INTO APPARTENIR VALUES (3, 1, 2);
INSERT INTO APPARTENIR VALUES (6, 1, 2);
INSERT INTO APPARTENIR VALUES (7, 1, 2);
INSERT INTO APPARTENIR VALUES (4, 1, 1);
INSERT INTO APPARTENIR VALUES (5, 1, 1);
INSERT INTO APPARTENIR VALUES (8, 1, 1);

INSERT INTO ENSEIGNER VALUES (1, 1, 1, 1);
INSERT INTO ENSEIGNER VALUES (1, 2, 1, 1);
INSERT INTO ENSEIGNER VALUES (9, 3, 1, 1);
INSERT INTO ENSEIGNER VALUES (1, 4, 1, 2);

INSERT INTO EVALUATION (EVAL_DATE, EVAL_MATR_ID, EVAL_COEF, EVAL_CLAS_ID, EVAL_PROF_ID) VALUES ('2010-10-14', 1, 1, 1, 1);
INSERT INTO EVALUATION (EVAL_DATE, EVAL_MATR_ID, EVAL_COEF, EVAL_CLAS_ID, EVAL_PROF_ID) VALUES ('2011-04-16', 1, 1, 1, 1);
INSERT INTO EVALUATION (EVAL_DATE, EVAL_MATR_ID, EVAL_COEF, EVAL_CLAS_ID, EVAL_PROF_ID) VALUES ('2011-04-16', 2, 1, 1, 1);
INSERT INTO EVALUATION (EVAL_DATE, EVAL_MATR_ID, EVAL_COEF, EVAL_CLAS_ID, EVAL_PROF_ID) VALUES ('2011-10-25', 4, 2, 2, 1);

INSERT INTO NOTES VALUES (2, 1, 15);
INSERT INTO NOTES VALUES (4, 1, 18);
INSERT INTO NOTES VALUES (5, 1, 9);
INSERT INTO NOTES VALUES (8, 1, 15);

INSERT INTO NOTES VALUES (2, 2, 12);
INSERT INTO NOTES VALUES (4, 2, 20);
INSERT INTO NOTES VALUES (5, 2, 7);
INSERT INTO NOTES VALUES (8, 2, 15);

INSERT INTO NOTES VALUES (2, 3, 17);
INSERT INTO NOTES VALUES (4, 3, 19);
INSERT INTO NOTES VALUES (5, 3, 14);
INSERT INTO NOTES VALUES (8, 3, 14);

INSERT INTO NOTES VALUES (3, 4, 19);
INSERT INTO NOTES VALUES (6, 4, 12);
INSERT INTO NOTES VALUES (7, 4, 10);
