DROP DATABASE IF EXISTS BD_ECOLE;

CREATE DATABASE BD_ECOLE;

USE BD_ECOLE;

CREATE
  TABLE NDLP_CLASSE
  (
    NDLP_CLASSE_ID    INTEGER auto_increment NOT NULL ,
    NDLP_CLAS_NOM   CHAR (6 ) NOT NULL ,
    CONSTRAINT NDLP_CLASSE_PK PRIMARY KEY (NDLP_CLASSE_ID)
  )ENGINE=InnoDB, CHARSET=UTF8;

CREATE
  TABLE NDLP_PERSONNE
  (
    NDLP_PERSONNE_ID  INTEGER auto_increment NOT NULL ,
    NDLP_PERS_NOM VARCHAR (30 ) NOT NULL,
    NDLP_PERS_PRENOM VARCHAR (30 ) NOT NULL ,
    NDLP_PERS_SEXE           CHAR (1 ) NOT NULL ,
    NDLP_PERS_ADR            VARCHAR (50 ) NOT NULL ,
    NDLP_PERS_CP             CHAR (5 ) NOT NULL ,
    NDLP_PERS_VILLE          VARCHAR (50 ) NOT NULL ,
    NDLP_PERS_DATE_NAISSANCE DATE NOT NULL ,
    NDLP_PERS_EMAIL          VARCHAR (100 ) ,
    NDLP_PERS_TEL            CHAR (10 ) ,
    CONSTRAINT NDLP_PERSONNE_PK PRIMARY KEY (NDLP_PERSONNE_ID)
  )ENGINE=InnoDB, CHARSET=UTF8;

CREATE
  TABLE NDLP_ELEVE
  (
    NDLP_ELEVE_ID INTEGER NOT NULL ,
    CONSTRAINT NDLP_ELEVE_PK PRIMARY KEY (NDLP_ELEVE_ID)
  )ENGINE=InnoDB, CHARSET=UTF8;

CREATE
  TABLE NDLP_PROFESSEUR
  (
    NDLP_PROFESSEUR_ID INTEGER NOT NULL,
    CONSTRAINT NDLP_PROFESSEUR_PK PRIMARY KEY (NDLP_PROFESSEUR_ID)
  )ENGINE=InnoDB, CHARSET=UTF8;

CREATE
  TABLE NDLP_MATIERE
  (
    NDLP_MATIERE_ID  INTEGER auto_increment NOT NULL ,
    NDLP_MATR_NOM_COURT VARCHAR (5 ) NOT NULL,
    NDLP_MATR_NOM_LONG VARCHAR (255 ) NOT NULL,
    CONSTRAINT NDLP_MATIERE_PK PRIMARY KEY (NDLP_MATIERE_ID)
  )ENGINE=InnoDB, CHARSET=UTF8;

CREATE
  TABLE NDLP_SESSION
  (
    NDLP_SESSION_ID INTEGER auto_increment NOT NULL ,
    NDLP_SESS_DATES  CHAR (9 ) ,
    CONSTRAINT NDLP_SESSION_PK PRIMARY KEY (NDLP_SESSION_ID)
  )ENGINE=InnoDB, CHARSET=UTF8;
  
CREATE
  TABLE NDLP_APPARTENIR
  (
    NDLP_APPA_ELEV_ID INTEGER NOT NULL ,
    NDLP_APPA_SESS_ID INTEGER NOT NULL ,
    NDLP_APPA_CLAS_ID INTEGER NOT NULL ,
    CONSTRAINT NDLP_APPARTENIR_PK PRIMARY KEY (NDLP_APPA_ELEV_ID, NDLP_APPA_SESS_ID, NDLP_APPA_CLAS_ID)
  )ENGINE=InnoDB, CHARSET=UTF8;

CREATE
  TABLE NDLP_ENSEIGNER
  (
    NDLP_ENSG_PROF_ID INTEGER NOT NULL ,
    NDLP_ENSG_MATR_ID  INTEGER NOT NULL ,
    NDLP_ENSG_CLAS_ID  INTEGER NOT NULL ,
    NDLP_ENSG_SESS_ID  INTEGER NOT NULL ,
    CONSTRAINT NDLP_ENSEIGNER_PK PRIMARY KEY (NDLP_ENSG_PROF_ID, NDLP_ENSG_MATR_ID, NDLP_ENSG_CLAS_ID, NDLP_ENSG_SESS_ID)
  )ENGINE=InnoDB, CHARSET=UTF8;

CREATE
  TABLE NDLP_EVALUATION
  (
    NDLP_EVALUATION_ID      INTEGER auto_increment NOT NULL ,
    NDLP_EVAL_DATE    DATE NOT NULL ,
    NDLP_EVAL_MATR_ID  INTEGER NOT NULL ,
    NDLP_EVAL_COEF    INTEGER NOT NULL ,
    NDLP_EVAL_CLAS_ID  INTEGER NOT NULL ,
    NDLP_EVAL_PROF_ID INTEGER NOT NULL ,
    CONSTRAINT NDLP_EVALUATION_PK PRIMARY KEY (NDLP_EVALUATION_ID)
  )ENGINE=InnoDB, CHARSET=UTF8;

CREATE
  TABLE NDLP_NOTES
  (
    NDLP_NOTE_ELEV_ID   INTEGER NOT NULL ,
    NDLP_NOTE_EVAL_ID INTEGER NOT NULL ,
    NDLP_NOTE_OBTENUE INTEGER NOT NULL ,
    CONSTRAINT NDLP_NOTES_PK PRIMARY KEY (NDLP_NOTE_ELEV_ID, NDLP_NOTE_EVAL_ID)
  )ENGINE=InnoDB, CHARSET=UTF8;


ALTER TABLE NDLP_APPARTENIR ADD CONSTRAINT NDLP_APPARTENIR_NDLP_ELEVE_FK
FOREIGN KEY ( NDLP_APPA_ELEV_ID ) REFERENCES NDLP_ELEVE ( NDLP_ELEVE_ID ) ;

ALTER TABLE NDLP_APPARTENIR ADD CONSTRAINT NDLP_ELEV_NDLP_CLAS_FK FOREIGN
KEY ( NDLP_APPA_CLAS_ID ) REFERENCES NDLP_CLASSE ( NDLP_CLASSE_ID ) ;

ALTER TABLE NDLP_APPARTENIR ADD CONSTRAINT NDLP_ELEV_NDLP_SESS_FK FOREIGN
KEY ( NDLP_APPA_SESS_ID ) REFERENCES NDLP_SESSION ( NDLP_SESSION_ID ) ;

ALTER TABLE NDLP_ELEVE ADD CONSTRAINT NDLP_ELEV_NDLP_PERS_FK FOREIGN KEY (
NDLP_ELEVE_ID ) REFERENCES NDLP_PERSONNE ( NDLP_PERSONNE_ID ) ;

ALTER TABLE NDLP_ENSEIGNER ADD CONSTRAINT NDLP_ENSG_NDLP_CLAS_FK FOREIGN
KEY ( NDLP_ENSG_CLAS_ID ) REFERENCES NDLP_CLASSE ( NDLP_CLASSE_ID ) ;

ALTER TABLE NDLP_ENSEIGNER ADD CONSTRAINT NDLP_ENSG_NDLP_MATR_FK
FOREIGN KEY ( NDLP_ENSG_MATR_ID ) REFERENCES NDLP_MATIERE ( NDLP_MATIERE_ID ) ;

ALTER TABLE NDLP_ENSEIGNER ADD CONSTRAINT NDLP_ENSG_NDLP_PROF_FK
FOREIGN KEY ( NDLP_ENSG_PROF_ID ) REFERENCES NDLP_PROFESSEUR ( NDLP_PROFESSEUR_ID ) ;

ALTER TABLE NDLP_ENSEIGNER ADD CONSTRAINT NDLP_ENSG_NDLP_SESS_FK
FOREIGN KEY ( NDLP_ENSG_SESS_ID ) REFERENCES NDLP_SESSION ( NDLP_SESSION_ID ) ;

ALTER TABLE NDLP_EVALUATION ADD CONSTRAINT NDLP_EVAL_NDLP_CLAS_FK
FOREIGN KEY ( NDLP_EVAL_CLAS_ID ) REFERENCES NDLP_CLASSE ( NDLP_CLASSE_ID ) ;

ALTER TABLE NDLP_EVALUATION ADD CONSTRAINT NDLP_EVAL_NDLP_MATR_FK
FOREIGN KEY ( NDLP_EVAL_MATR_ID ) REFERENCES NDLP_MATIERE ( NDLP_MATIERE_ID ) ;

ALTER TABLE NDLP_EVALUATION ADD CONSTRAINT NDLP_EVAL_NDLP_PROF_FK
FOREIGN KEY ( NDLP_EVAL_PROF_ID ) REFERENCES NDLP_PROFESSEUR ( NDLP_PROFESSEUR_ID ) ;

ALTER TABLE NDLP_NOTES ADD CONSTRAINT NDLP_NOTE_NDLP_ELEV_FK FOREIGN KEY (
NDLP_NOTE_ELEV_ID ) REFERENCES NDLP_ELEVE ( NDLP_ELEVE_ID ) ;

ALTER TABLE NDLP_NOTES ADD CONSTRAINT NDLP_NOTE_NDLP_EVAL_FK FOREIGN KEY
( NDLP_NOTE_EVAL_ID ) REFERENCES NDLP_EVALUATION ( NDLP_EVALUATION_ID ) ;

ALTER TABLE NDLP_PROFESSEUR ADD CONSTRAINT NDLP_PROF_NDLP_PERS_FK
FOREIGN KEY ( NDLP_PROFESSEUR_ID ) REFERENCES NDLP_PERSONNE ( NDLP_PERSONNE_ID ) ;
